const darkLayout={paper_bgcolor:'rgba(0,0,0,0)',plot_bgcolor:'rgba(0,0,0,0)',font:{color:'#cfe6f2',size:11},margin:{l:42,r:40,t:18,b:42},xaxis:{gridcolor:'rgba(80,140,170,.12)',zerolinecolor:'rgba(180,230,255,.15)',tickfont:{color:'#8ea6b6'}},yaxis:{gridcolor:'rgba(80,140,170,.12)',zerolinecolor:'rgba(180,230,255,.15)',tickfont:{color:'#8ea6b6'}},legend:{orientation:'h',x:0,y:1.12,font:{size:11}},hovermode:'x unified'};
const cfg={responsive:true,displaylogo:false,modeBarButtonsToRemove:['lasso2d','select2d']};
function plotEnergy(id,full=false){const d=HOME_DAILY;Plotly.newPlot(id,[
{x:d.map(r=>r.date),y:d.map(r=>r.solar),name:'Solar kWh',type:'scatter',mode:'lines',line:{color:'#34f56a',width:2},fill:'tozeroy',fillcolor:'rgba(52,245,106,.10)'},
{x:d.map(r=>r.date),y:d.map(r=>r.home),name:'House load kWh',type:'scatter',mode:'lines',line:{color:'#2277ff',width:2}},
{x:d.map(r=>r.date),y:d.map(r=>r.import),name:'Grid import kWh',type:'scatter',mode:'lines',line:{color:'#ff4e42',width:1.7}},
{x:d.map(r=>r.date),y:d.map(r=>r.export),name:'Grid export kWh',type:'scatter',mode:'lines',line:{color:'#00d7ff',width:1.7},fill:'tozeroy',fillcolor:'rgba(0,215,255,.12)'},
{x:d.map(r=>r.date),y:d.map(r=>r.gas),name:'Gas MJ/day',type:'scatter',mode:'lines',yaxis:'y2',line:{color:'#ff7a18',width:1.8}}
],{...darkLayout,height:full?720:null,yaxis:{...darkLayout.yaxis,title:'kWh/day'},yaxis2:{title:'Gas MJ/day',overlaying:'y',side:'right',gridcolor:'rgba(0,0,0,0)'},xaxis:{...darkLayout.xaxis,rangeslider:{visible:true,thickness:.06},rangeselector:{buttons:[{count:30,label:'30D',step:'day',stepmode:'backward'},{count:90,label:'90D',step:'day',stepmode:'backward'},{count:6,label:'6M',step:'month',stepmode:'backward'},{step:'all',label:'ALL'}],bgcolor:'rgba(12,42,62,.6)',font:{color:'#cfe6f2'},activecolor:'#123e5a'}}},cfg)}
function plotWater(id,full=false){const w=HOME_DATA.water;Plotly.newPlot(id,[
{x:w.map(r=>r.issue),y:w.map(r=>r.kl),name:'Bill usage kL',type:'bar',marker:{color:'#00d7ff'},opacity:.85},
{x:w.map(r=>r.issue),y:w.map(r=>r.check?null:r.lpd),name:'L/day',type:'scatter',mode:'lines+markers',yaxis:'y2',line:{color:'#34f56a',shape:'hv',width:2},marker:{size:5}},
{x:w.filter(r=>r.check).map(r=>r.issue),y:w.filter(r=>r.check).map(r=>r.lpd),name:'Check interval',type:'scatter',mode:'markers',yaxis:'y2',marker:{color:'#ffc928',size:10,symbol:'triangle-up'}}
],{...darkLayout,height:full?720:null,barmode:'overlay',yaxis:{...darkLayout.yaxis,title:'kL per bill'},yaxis2:{title:'L/day',overlaying:'y',side:'right',gridcolor:'rgba(0,0,0,0)',range:[0,900]},xaxis:{...darkLayout.xaxis,tickformat:'%b\n%Y',dtick:'M3'}},cfg)}
function plotWeather(id,full=false){const d=HOME_DAILY;Plotly.newPlot(id,[
{x:d.map(r=>r.date),y:d.map(r=>r.temp),name:'Mean temp °C',type:'scatter',mode:'lines',line:{color:'#ffc928',width:2},fill:'tozeroy',fillcolor:'rgba(255,201,40,.08)'},
{x:d.map(r=>r.date),y:d.map(r=>r.rain),name:'Rainfall mm',type:'bar',yaxis:'y2',marker:{color:'#00d7ff'},opacity:.45}
],{...darkLayout,height:full?720:null,yaxis:{...darkLayout.yaxis,title:'°C'},yaxis2:{title:'Rain mm',overlaying:'y',side:'right',gridcolor:'rgba(0,0,0,0)'},xaxis:{...darkLayout.xaxis,rangeslider:{visible:true,thickness:.06}}},cfg)}
function plotCosts(id,full=false){const d=HOME_DAILY;Plotly.newPlot(id,[{x:d.map(r=>r.date),y:d.map(r=>r.cost),name:'Daily cost $',type:'bar',marker:{color:'#b466ff'},opacity:.7},{x:d.map(r=>r.date),y:d.map(r=>movingAvg(d.map(x=>x.cost),14)),name:'14 day avg',type:'scatter',mode:'lines',line:{color:'#ff7a18',width:2}}],{...darkLayout,height:full?720:null,yaxis:{...darkLayout.yaxis,title:'$/day'},xaxis:{...darkLayout.xaxis,rangeslider:{visible:true,thickness:.06}}},cfg)}
function plotGas(id,full=false){const d=HOME_DAILY;Plotly.newPlot(id,[{x:d.map(r=>r.date),y:d.map(r=>r.gas),name:'Gas MJ/day',type:'scatter',mode:'lines',line:{color:'#ff7a18',shape:'hv',width:2},fill:'tozeroy',fillcolor:'rgba(255,122,24,.12)'},{x:d.map(r=>r.date),y:movingAvg(d.map(r=>r.temp),7),name:'Temp °C 7-day',type:'scatter',mode:'lines',yaxis:'y2',line:{color:'#ffc928',width:1.8}}],{...darkLayout,height:full?720:null,yaxis:{...darkLayout.yaxis,title:'MJ/day'},yaxis2:{title:'°C',overlaying:'y',side:'right',gridcolor:'rgba(0,0,0,0)'},xaxis:{...darkLayout.xaxis,rangeslider:{visible:true,thickness:.06}}},cfg)}
function movingAvg(arr,n){return arr.map((_,i)=>{let s=0,c=0;for(let j=Math.max(0,i-n+1);j<=i;j++){s+=Number(arr[j]);c++}return +(s/c).toFixed(2)})}
