(() => {
'use strict';
const liveSamples=[]; const charts=new Map();
const enabledSeries={electricity:new Set(['import','export'])};
const history=()=>window.HOME_INSIGHTS_ELECTRICITY_HISTORY||{daily:[],monthly:[],yearly:[]};
const css=n=>getComputedStyle(document.body).getPropertyValue(n).trim();
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function addLiveSample(sample){liveSamples.push({...sample,time:new Date(sample.time||Date.now())});while(liveSamples.length>720)liveSamples.shift();render('electricity');render('battery');render('solar');}
function fmtDate(v,kind){const d=new Date(v+(v.length===7?'-01':'T12:00:00'));return kind==='month'?d.toLocaleDateString('en-AU',{month:'short',year:'2-digit'}):d.toLocaleDateString('en-AU',{day:'numeric',month:'short'});}
function electricityData(range){
 if(range==='live') return {rows:liveSamples.map(x=>({label:x.time.toLocaleTimeString('en-AU',{hour:'2-digit',minute:'2-digit'}),import:Math.max(0,x.grid||0),export:Math.max(0,-(x.grid||0)),net:x.grid||0})),unit:'kW',coverage:'Page-open live readings'};
 const h=history(); let source,kind;
 if(range==='30'){source=h.daily.slice(-30);kind='day'} else if(range==='365'){source=h.daily.slice(-365);kind='day'} else if(range.startsWith('year:')){const yr=range.split(':')[1];source=h.monthly.filter(r=>String(r.month).startsWith(yr));kind='month'} else {source=h.monthly;kind='month'}
 const coverage=range==='all'?'Jan 2019 – Sep 2025':range==='365'?'Latest 365 recorded days':range.startsWith('year:')?range.split(':')[1]:'Latest 30 recorded days';
 return {rows:source.map(r=>({label:kind==='month'?fmtDate(r.month,'month'):fmtDate(r.date,'day'),import:+r.importKwh,export:+r.exportKwh,net:+r.importKwh-(+r.exportKwh)})),unit:'kWh',coverage};
}
function genericData(type,range){const rows=(window.HOME_INSIGHTS_DAILY||[]).slice(-(Number(range)||30));if(type==='battery')return{rows:range==='live'?liveSamples.map(x=>({label:x.time.toLocaleTimeString('en-AU',{hour:'2-digit',minute:'2-digit'}),soc:x.soc})):rows.map(r=>({label:fmtDate(r.date,'day'),soc:+r.batterySocEnd})),series:[['soc','Battery','--battery']],unit:'%'};if(type==='solar')return{rows:range==='live'?liveSamples.map(x=>({label:x.time.toLocaleTimeString('en-AU',{hour:'2-digit',minute:'2-digit'}),solar:x.solar})):rows.map(r=>({label:fmtDate(r.date,'day'),solar:+r.solarKwh})),series:[['solar','Solar','--solar']],unit:range==='live'?'kW':'kWh'};return{rows:rows.map(r=>({label:fmtDate(r.date,'day'),electricity:+r.electricityTotal,gas:+r.gasTotal,water:+r.waterTotal})),series:[['electricity','Electricity','--grid'],['gas','Gas','--gas'],['water','Water','--water']],unit:'$'};}
function smoothPath(points){if(points.length<2)return'';let d=`M ${points[0][0]} ${points[0][1]}`;for(let i=1;i<points.length;i++){const [x0,y0]=points[i-1],[x1,y1]=points[i],mx=(x0+x1)/2;d+=` C ${mx} ${y0}, ${mx} ${y1}, ${x1} ${y1}`;}return d;}
function render(type){const state=charts.get(type);if(!state)return;const el=document.getElementById(type+'Chart');if(!el)return;let d,series;
 if(type==='electricity'){d=electricityData(state.range);const all=[['import','Import','--grid'],['export','Export','--solar'],['net','Net grid','--battery']];series=all.filter(([k])=>enabledSeries.electricity.has(k));updateKpis(d.rows,d.coverage,d.unit);}else{d=genericData(type,state.range);series=d.series;}
 const rows=d.rows.filter(r=>series.some(([k])=>Number.isFinite(r[k])));if(rows.length<2){el.innerHTML=`<div class="chart-empty"><div><strong>${state.range==='live'?'Collecting live readings':'No data for this view'}</strong><span>${state.range==='live'?'Keep the page open while live readings arrive.':'Historical data is not available for this series yet.'}</span></div></div>`;return;}
 const W=1100,H=360,p={l:60,r:24,t:28,b:46};const vals=[];rows.forEach(r=>series.forEach(([k])=>{if(Number.isFinite(r[k]))vals.push(r[k])}));let min=Math.min(0,...vals),max=Math.max(0,...vals);if(max===min)max=min+1;const x=i=>p.l+(i/(rows.length-1))*(W-p.l-p.r),y=v=>p.t+(max-v)/(max-min)*(H-p.t-p.b);
 let svg=`<svg viewBox="0 0 ${W} ${H}" role="img"><defs>`;series.forEach(([k,l,v])=>{const c=css(v);svg+=`<linearGradient id="g-${type}-${k}" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="${c}" stop-opacity=".28"/><stop offset="1" stop-color="${c}" stop-opacity="0"/></linearGradient>`});svg+=`</defs>`;
 for(let i=0;i<5;i++){const yy=p.t+i*(H-p.t-p.b)/4,val=max-i*(max-min)/4;svg+=`<line class="chart-grid" x1="${p.l}" x2="${W-p.r}" y1="${yy}" y2="${yy}"/><text class="chart-axis-text" x="${p.l-10}" y="${yy+4}" text-anchor="end">${formatVal(val,d.unit)}</text>`}
 const tick=Math.max(1,Math.ceil(rows.length/7));rows.forEach((r,i)=>{if(i%tick===0||i===rows.length-1)svg+=`<text class="chart-axis-text" x="${x(i)}" y="${H-12}" text-anchor="middle">${esc(r.label)}</text>`});
 series.forEach(([k,l,v])=>{const pts=rows.map((r,i)=>Number.isFinite(r[k])?[x(i),y(r[k])]:null).filter(Boolean);if(pts.length<2)return;const path=smoothPath(pts),base=y(0),color=css(v);svg+=`<path class="chart-area" d="${path} L ${pts[pts.length-1][0]} ${base} L ${pts[0][0]} ${base} Z" fill="url(#g-${type}-${k})"/><path class="chart-smooth-line" style="stroke:${color}" d="${path}"/>`;});
 rows.forEach((r,i)=>svg+=`<rect class="chart-hit" data-i="${i}" x="${Math.max(p.l,x(i)-(W-p.l-p.r)/rows.length/2)}" y="${p.t}" width="${Math.max(8,(W-p.l-p.r)/rows.length)}" height="${H-p.t-p.b}" fill="transparent"/>`);svg+=`</svg><div class="chart-crosshair" hidden></div><div class="chart-tooltip" hidden></div>`;el.innerHTML=svg;
 const tip=el.querySelector('.chart-tooltip'),cross=el.querySelector('.chart-crosshair');el.querySelectorAll('.chart-hit').forEach(hit=>{const show=()=>{const i=+hit.dataset.i,r=rows[i];tip.innerHTML=`<b>${esc(r.label)}</b>`+series.filter(([k])=>Number.isFinite(r[k])).map(([k,l])=>`<div><span>${l}</span><strong>${formatVal(r[k],d.unit)}</strong></div>`).join('');tip.hidden=false;cross.hidden=false;const pct=x(i)/W*100;tip.style.left=`${pct}%`;tip.style.top='12%';cross.style.left=`${pct}%`;};hit.addEventListener('pointerenter',show);hit.addEventListener('pointermove',show);hit.addEventListener('pointerleave',()=>{tip.hidden=true;cross.hidden=true});hit.addEventListener('click',show);});}
function updateKpis(rows,coverage,unit){if(!document.getElementById('historyImport'))return;const imp=rows.reduce((s,r)=>s+(Number.isFinite(r.import)?r.import:0),0),exp=rows.reduce((s,r)=>s+(Number.isFinite(r.export)?r.export:0),0);document.getElementById('historyImport').textContent=`${imp.toLocaleString('en-AU',{maximumFractionDigits:1})} ${unit}`;document.getElementById('historyExport').textContent=`${exp.toLocaleString('en-AU',{maximumFractionDigits:1})} ${unit}`;document.getElementById('historyNet').textContent=`${(imp-exp).toLocaleString('en-AU',{maximumFractionDigits:1})} ${unit}`;document.getElementById('historyCoverage').textContent=coverage;}
function formatVal(v,u){if(u==='$')return new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD',maximumFractionDigits:2}).format(v);return`${Math.abs(v)>=100?Math.round(v).toLocaleString('en-AU'):Math.abs(v)>=10?v.toFixed(1):v.toFixed(2)} ${u}`;}
function init(){document.querySelectorAll('[data-series-toggle]').forEach(g=>g.querySelectorAll('button[data-series]').forEach(btn=>btn.addEventListener('click',()=>{const set=enabledSeries[g.dataset.seriesToggle],k=btn.dataset.series;if(set.has(k)){if(set.size>1){set.delete(k);btn.classList.remove('active')}}else{set.add(k);btn.classList.add('active')}render(g.dataset.seriesToggle)})));document.querySelectorAll('[data-chart-range]').forEach(g=>{const type=g.dataset.chartRange;charts.set(type,{range:g.querySelector('.active')?.dataset.range||'30'});g.querySelectorAll('button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll(`[data-chart-range=\"${type}\"] button,[data-chart-range-secondary=\"${type}\"] button`).forEach(b=>b.classList.remove('active'));btn.classList.add('active');charts.get(type).range=btn.dataset.range;render(type)}));render(type)});document.querySelectorAll('[data-chart-range-secondary]').forEach(g=>{const type=g.dataset.chartRangeSecondary;g.querySelectorAll('button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll(`[data-chart-range=\"${type}\"] button,[data-chart-range-secondary=\"${type}\"] button`).forEach(b=>b.classList.remove('active'));btn.classList.add('active');charts.get(type).range=btn.dataset.range;render(type)}))});}
window.HomeInsightsCharts={init,renderAll:()=>charts.forEach((_,k)=>render(k)),addLiveSample};
})();
