(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  const text = (id, value) => { const el=$(id); if(el && value!==undefined && value!==null) el.textContent=value; };
  const read = id => $(id)?.textContent?.trim() || '—';
  const log = message => { const list=$('cpEventLog'); if(!list)return; const li=document.createElement('li'),time=document.createElement('time'),span=document.createElement('span'); time.textContent=new Date().toLocaleTimeString('en-AU',{hour:'2-digit',minute:'2-digit'}); span.textContent=message; li.append(time,span); list.prepend(li); while(list.children.length>7)list.lastElementChild.remove(); };
  const numeric = value => { const n=Number(String(value??'').replace(/[^0-9.-]/g,'')); return Number.isFinite(n)?n:null; };
  const fmtKw = value => value==null?'—':`${Math.abs(value).toFixed(value<10?2:1)} kW`;
  let liveSamples=[], controls=[];

  function tick(){ const now=new Date(); text('cockpitTime',now.toLocaleTimeString('en-AU',{hour12:false})); text('cockpitDate',now.toLocaleDateString('en-AU',{weekday:'short',day:'2-digit',month:'short',year:'numeric'}).toUpperCase()); const start=new Date(now),end=new Date(now); start.setHours(11,0,0,0); end.setHours(14,0,0,0); const free=now>=start&&now<end; $('cockpitTariff')?.classList.toggle('free',free); $('cockpitTariff')?.querySelector('b')?.replaceChildren(document.createTextNode(free?'FREE GRID':'PAID GRID')); const target=free?end:(now<start?start:new Date(start.getTime()+86400000)); const mins=Math.max(0,Math.ceil((target-now)/60000)); text('cockpitTariffCountdown',free?`${Math.floor(mins/60)}h ${mins%60}m remaining`:`${Math.floor(mins/60)}h ${mins%60}m to FREE`); }
  function mirror(){ text('cpElectricityCost',read('homeElectricityCost')); text('cpGasCost',read('homeGasCost')); text('cpWaterCost',read('homeWaterCost')); text('cpTotalCost',read('homeTotalCost')); text('cpGasUse',read('gasLatestMj')); const water=read('waterLatestUsage')||read('waterLastReading'); if(water!=='—')text('cpWaterUse',water); text('cpWeatherIcon',read('weatherHeroIcon')); text('cpOutsideTemp',read('weatherHeroTemp')); text('cpWeatherText',read('weatherHeroText').toUpperCase()); text('cpFeels',read('feelsLike')); text('cpHumidity',read('humidity')); text('cpWind',read('windSpeed')); text('cpRain',read('rainChance')); const first=$('forecastList')?.querySelector('.forecast-row strong'); if(first)text('cpForecast',first.textContent); }
  function spark(id,values){ const svg=$(id); if(!svg||values.length<2)return; const max=Math.max(1,...values),min=Math.min(...values),range=Math.max(.01,max-min); const pts=values.map((v,i)=>`${(i/(values.length-1)*160).toFixed(1)},${(35-(v-min)/range*31).toFixed(1)}`).join(' '); svg.innerHTML=`<polyline points="${pts}"/>`; }
  function linePoints(values,width,height,min,max){return values.map((v,i)=>`${(i/Math.max(1,values.length-1)*width).toFixed(1)},${(height-(v-min)/Math.max(.01,max-min)*height).toFixed(1)}`).join(' ');}
  function renderLiveChart(){const svg=$('cpLiveChart');if(!svg||liveSamples.length<2)return;const series={solar:liveSamples.map(x=>Number(x.solar)||0),house:liveSamples.map(x=>Number(x.house)||0),grid:liveSamples.map(x=>Number(x.grid)||0),battery:liveSamples.map(x=>Number(x.battery)||0)};const all=Object.values(series).flat(),abs=Math.max(2,...all.map(Math.abs)),min=-abs,max=abs;svg.innerHTML=Object.entries(series).map(([key,values])=>`<polyline class="${key}" points="${linePoints(values,900,230,min,max)}"/>`).join('');const peak=Math.max(...series.house);const solar=series.solar.at(-1)||0,house=series.house.at(-1)||0,grid=series.grid.at(-1)||0;text('cpPeakLoad',fmtKw(peak));text('cpSolarShare',`${Math.min(100,house?solar/house*100:0).toFixed(0)}%`);text('cpNetGrid',fmtKw(grid));text('cpSelfPowered',`${Math.max(0,Math.min(100,house?(house-Math.max(0,grid))/house*100:100)).toFixed(0)}%`);}
  function renderHistory(){const svg=$('cpHistoryChart'),daily=(window.HOME_INSIGHTS_DAILY||[]).slice(-14);if(!svg||daily.length<2)return;const series={solar:daily.map(x=>Number(x.solarKwh??x.solar)||0),grid:daily.map(x=>Number(x.importKwh??x.gridImport)||0),house:daily.map(x=>Number(x.loadKwh??x.load)||0)},max=Math.max(1,...Object.values(series).flat());svg.innerHTML=Object.entries(series).map(([key,values])=>`<polyline class="${key}" points="${linePoints(values,900,190,0,max)}"/>`).join('');}
  function live(sample){ liveSamples.push(sample); if(liveSamples.length>30)liveSamples.shift(); const solar=numeric(sample.solar)||0,house=numeric(sample.house)||0,grid=numeric(sample.grid)||0,battery=numeric(sample.battery)||0,soc=numeric(sample.soc); text('cpSolar',fmtKw(solar)); text('cpHouse',fmtKw(house)); text('cpGrid',fmtKw(grid)); text('cpGridMode',grid>0.02?'IMPORT':grid<-.02?'EXPORT':'IDLE'); text('cpBattery',fmtKw(battery)); text('cpBatteryMode',battery>.02?'CHARGING':battery<-.02?'DISCHARGING':'IDLE'); if(soc!=null){text('cpSoc',`${soc.toFixed(1)}%`); ['cpSocBar','cpBatteryFill'].forEach(id=>{if($(id))$(id).style.width=`${Math.max(0,Math.min(100,soc))}%`;});} text('cockpitUpdated',`Telemetry ${new Date(sample.time||Date.now()).toLocaleTimeString('en-AU')}`); document.querySelector('.cockpit-status')?.classList.add('online'); text('cockpitLinkState','LIVE'); spark('cpElectricitySpark',liveSamples.map(x=>Math.abs(numeric(x.house)||0))); renderLiveChart(); }
  function sharedDay(row){ text('cpElectricityUse',`${(Number(row.loadKwh)||0).toFixed(1)} kWh`); const daily=window.HOME_INSIGHTS_DAILY||[]; spark('cpGasSpark',daily.slice(-18).map(x=>Number(x.gasMJ)||0)); spark('cpWaterSpark',daily.slice(-18).map(x=>Number(x.waterL||x.water)||0)); renderHistory(); }
  function renderControls(){ const box=$('cpControls'),message=$('cpControlMessage'); if(!box)return; box.innerHTML=''; if(!controls.length){if(message)message.hidden=false;return;} if(message)message.hidden=true; controls.forEach(c=>{const button=document.createElement('button'); button.className='cp-control'; button.dataset.id=c.id; button.innerHTML=`<span>${String(c.name||c.id).replace(/[<>]/g,'')}</span><small>${String(c.domain||'').toUpperCase()} · ${String(c.kind||'toggle').toUpperCase()}</small><b>${String(c.state||'—').toUpperCase()}</b>`; button.addEventListener('click',()=>activate(button,c)); box.appendChild(button); }); }
  async function activate(button,control){ if(!window.confirm(`Send ${control.nextLabel||'command'} to ${control.name}?`))return; button.classList.add('pending'); try{const result=await window.HomeInsightsApi.request(window.HomeInsights.cfg.sharedApi,{action:'control',payload:JSON.stringify({id:control.id,command:control.nextCommand})}); if(!result.ok)throw new Error(result.error||'Command failed'); button.querySelector('b').textContent=String(result.state||'SENT').toUpperCase(); log(`${control.name}: command accepted`); setTimeout(loadStatus,800);}catch(error){log(`${control.name}: ${error.message}`);}finally{button.classList.remove('pending');} }
  async function loadStatus(){ const api=window.HomeInsights?.cfg?.sharedApi; if(!api){text('cpHaStatus','NOT CONFIGURED');return;} try{const json=await window.HomeInsightsApi.request(api,{action:'cockpit'}); if(!json.ok)throw new Error(json.error||'Status failed'); text('cpHaStatus','ONLINE'); text('cpHaDetail',`${json.ha?.entities||0} entities · ${json.ha?.version||'HA'}`); text('cpRecorder',String(json.status?.historyStatus||'ONLINE').toUpperCase()); text('cpRecorderDetail',`${json.status?.dailyRecords||0} daily records`); if(json.infrastructure?.internet){text('cpInternet',json.infrastructure.internet.value);text('cpInternetDetail',json.infrastructure.internet.name);} if(json.infrastructure?.network){text('cpNetwork',json.infrastructure.network.value);text('cpNetworkDetail',json.infrastructure.network.name);} controls=json.controls||[]; renderControls(); log('Home Assistant status synchronised'); }catch(error){text('cpHaStatus','OFFLINE');text('cpHaDetail',error.message);log(`Bridge unavailable: ${error.message}`);} }
  async function preloadLiveGraph(){const api=window.HomeInsights?.cfg?.sharedApi;if(!api)return;try{const json=await window.HomeInsightsApi.request(api,{action:'samples',date:window.HomeInsights.dayKey()});if(!json.ok)return;liveSamples=(json.samples||[]).slice(-30).map(sample=>({time:sample.timestamp,solar:Number(sample.solar)||0,house:Number(sample.house)||0,battery:Number(sample.batteryPower)||0,soc:Number(sample.batterySoc),grid:(Number(sample.gridImport)||0)>0?Number(sample.gridImport)||0:-Math.abs(Number(sample.gridExport)||0)}));renderLiveChart();if(liveSamples.length)live(liveSamples.pop());log(`${liveSamples.length+1} recorded power samples loaded`);}catch(error){console.warn('Cockpit samples:',error);}}
  function start(){ tick();setInterval(tick,1000);setInterval(mirror,3000);mirror(); window.addEventListener('homeinsights:live',e=>live(e.detail||{})); window.addEventListener('homeinsights:shared-day',e=>sharedDay(e.detail||{})); document.addEventListener('click',e=>{if(e.target.closest('[data-page-link="cockpit"]'))setTimeout(()=>{mirror();loadStatus();preloadLiveGraph();},0);}); setTimeout(loadStatus,1200);setTimeout(preloadLiveGraph,1400); }
  window.HomeInsightsCockpit={start,loadStatus};
})();
