(() => {
  'use strict';
  const { $ } = window.HomeInsights;
  const meterKey = 'home-insights-meter-readings';
  const photoDbName = 'home-insights-meter-photos';
  let meterKind = 'gas', selectedPhotoFile = null, previewUrl = '', ocrOriginal = null, ocrAttempted = false;
  const liveRows = [];
  const readMeters = () => { try { return JSON.parse(localStorage.getItem(meterKey) || '[]'); } catch { return []; } };
  const writeMeters = rows => localStorage.setItem(meterKey, JSON.stringify(rows));
  const localDateValue = date => new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);
  function openPhotoDb(){return new Promise((resolve,reject)=>{const request=indexedDB.open(photoDbName,1);request.onupgradeneeded=()=>request.result.createObjectStore('photos');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
  async function photoOperation(mode,id,value){const db=await openPhotoDb();return new Promise((resolve,reject)=>{const tx=db.transaction('photos',mode==='get'?'readonly':'readwrite'),store=tx.objectStore('photos'),request=mode==='put'?store.put(value,id):mode==='delete'?store.delete(id):store.get(id);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);tx.oncomplete=()=>db.close();});}
  const getReadingPhoto=id=>photoOperation('get',id),deleteReadingPhoto=id=>photoOperation('delete',id).catch(()=>{});
  async function compactPhoto(file){if(!file.type.startsWith('image/'))throw new Error('Please choose an image file.');if(!window.createImageBitmap)return file;const bitmap=await createImageBitmap(file),scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close?.();return new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('Photo could not be prepared.')),'image/jpeg',.84));}
  function exifDateFromJpeg(buffer){const view=new DataView(buffer);if(view.byteLength<12||view.getUint16(0,false)!==0xffd8)return null;let offset=2;while(offset+4<view.byteLength){if(view.getUint8(offset)!==0xff)break;const marker=view.getUint8(offset+1),length=view.getUint16(offset+2,false);if(marker===0xe1&&length>=10&&view.getUint32(offset+4,false)===0x45786966){const tiff=offset+10,little=view.getUint16(tiff,false)===0x4949,u16=p=>view.getUint16(p,little),u32=p=>view.getUint32(p,little);const readAscii=(entry,count)=>{const start=count<=4?entry+8:tiff+u32(entry+8);if(start<0||start+count>view.byteLength)return'';let text='';for(let i=0;i<count-1;i++)text+=String.fromCharCode(view.getUint8(start+i));return text;};const readIfd=address=>{if(address<0||address+2>view.byteLength)return{};const found={},count=u16(address);for(let i=0;i<count;i++){const entry=address+2+i*12;if(entry+12>view.byteLength)break;const tag=u16(entry),type=u16(entry+2),items=u32(entry+4);if((tag===0x9003||tag===0x9004||tag===0x0132)&&type===2)found[tag]=readAscii(entry,items);if(tag===0x8769)found.exifOffset=u32(entry+8);}return found;};const first=readIfd(tiff+u32(tiff+4)),exif=first.exifOffset?readIfd(tiff+first.exifOffset):{};return exif[0x9003]||exif[0x9004]||first[0x0132]||null;}if(!length)break;offset+=2+length;}return null;}
  function parseExifDate(text){const match=String(text||'').match(/(\d{4}):(\d{2}):(\d{2})\s+(\d{2}):(\d{2})(?::(\d{2}))?/);return match?new Date(+match[1],+match[2]-1,+match[3],+match[4],+match[5],+(match[6]||0)):null;}
  function dateFromFilename(name){const match=String(name||'').match(/(?:^|\D)(20\d{2})[-_.]?(\d{2})[-_.]?(\d{2})[ T_-]?(\d{2})?[._-]?(\d{2})?[._-]?(\d{2})?(?:\D|$)/);return match?new Date(+match[1],+match[2]-1,+match[3],+(match[4]||12),+(match[5]||0),+(match[6]||0)):null;}
  async function extractPhotoDate(file){try{if(/jpe?g/i.test(file.type)||/\.jpe?g$/i.test(file.name)){const exif=parseExifDate(exifDateFromJpeg(await file.arrayBuffer()));if(exif)return{date:exif,source:'Photo capture date found'};}}catch{}const named=dateFromFilename(file.name);if(named)return{date:named,source:'Date found in filename'};return file.lastModified?{date:new Date(file.lastModified),source:'Using photo file date'}:null;}
  function clearSelectedPhoto(){selectedPhotoFile=null;ocrOriginal=null;ocrAttempted=false;$('meterPhoto').value='';if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl='';$('meterPhotoPreview').hidden=true;$('meterPhotoDrop').classList.remove('dragging');if($('meterOcrStatus'))$('meterOcrStatus').textContent='The original OCR attempt and your corrected reading are saved separately for auditability.';}
  async function attemptOcr(file){ocrAttempted=true;const status=$('meterOcrStatus');status.textContent='Attempting to read the meter…';try{if(!('TextDetector' in window))throw new Error('Browser OCR is unavailable');const detector=new TextDetector(),bitmap=await createImageBitmap(file),blocks=await detector.detect(bitmap);bitmap.close?.();const raw=blocks.map(block=>block.rawValue).join(' ').trim();ocrOriginal=raw||null;const candidates=raw.match(/\d[\d\s,.]{2,}/g)||[],best=candidates.map(value=>value.replace(/\s/g,'').replace(',','.')).find(value=>Number.isFinite(Number(value)));if(best&&!$('meterValue').value)$('meterValue').value=best;status.textContent=raw?`OCR found “${raw}”. Check and correct the reading before saving.`:'OCR attempted but found no readable digits. Enter the reading manually.';}catch{status.textContent='OCR attempted but is not supported by this browser. Enter the reading manually; the failed attempt is recorded.';}}
  async function handlePhoto(file){if(!file||!file.type.startsWith('image/')){alert('Please drop an image file.');return;}clearSelectedPhoto();selectedPhotoFile=file;previewUrl=URL.createObjectURL(file);$('meterPreview').src=previewUrl;$('meterPhotoName').textContent=file.name||'Meter photo';$('meterPhotoDateStatus').textContent='Checking photo date…';$('meterPhotoPreview').hidden=false;const [found]=await Promise.all([extractPhotoDate(file),attemptOcr(file)]);if(selectedPhotoFile!==file)return;if(found){$('meterDate').value=localDateValue(found.date);$('meterPhotoDateStatus').textContent=`${found.source}: ${found.date.toLocaleString('en-AU')}`;}else $('meterPhotoDateStatus').textContent='No date found — using the current date; adjust it if needed';}
  function ensurePhotoViewer(){let viewer=document.querySelector('.meter-photo-viewer');if(viewer)return viewer;viewer=document.createElement('div');viewer.className='meter-photo-viewer';viewer.hidden=true;viewer.innerHTML='<button type="button" aria-label="Close photo">×</button><img alt="Saved meter photograph">';const close=()=>{viewer.hidden=true;if(viewer.dataset.url)URL.revokeObjectURL(viewer.dataset.url);viewer.dataset.url='';viewer.querySelector('img').removeAttribute('src');};viewer.addEventListener('click',event=>{if(event.target===viewer||event.target.tagName==='BUTTON')close();});document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!viewer.hidden)close();});document.body.appendChild(viewer);return viewer;}
  async function hydratePhotoThumbnails(root=document){const buttons=[...root.querySelectorAll('[data-meter-photo]:not([data-photo-ready])')];await Promise.all(buttons.map(async button=>{button.dataset.photoReady='1';try{const blob=await getReadingPhoto(button.dataset.meterPhoto);if(!blob){button.remove();return;}const url=URL.createObjectURL(blob),img=document.createElement('img');img.src=url;img.alt='Saved meter photo';img.onload=()=>URL.revokeObjectURL(url);button.classList.remove('is-loading');button.appendChild(img);button.addEventListener('click',async()=>{const full=await getReadingPhoto(button.dataset.meterPhoto);if(!full)return;const viewer=ensurePhotoViewer(),fullUrl=URL.createObjectURL(full);viewer.dataset.url=fullUrl;viewer.querySelector('img').src=fullUrl;viewer.hidden=false;});}catch{button.remove();}}));}
  const photoButton=row=>(row.hasPhoto||row.source==='manual-with-photo')?`<button type="button" class="meter-photo-thumb is-loading" data-meter-photo="${row.id}" aria-label="Open saved meter photo"></button>`:'';
  function renderMeters() {
    const rows = readMeters().sort((a,b) => b.date.localeCompare(a.date));
    ['gas','water'].forEach(kind => { const row = rows.find(item => item.kind === kind); $(`${kind}LastReading`).textContent = row ? row.value : '—'; $(`${kind}LastDate`).textContent = row ? new Date(row.date).toLocaleString('en-AU',{day:'numeric',month:'short',year:'numeric',hour:'numeric',minute:'2-digit'}) : 'No reading saved'; });
    $('meterRecords').innerHTML = rows.length ? rows.map(row => `<div class="record-row${row.hasPhoto||row.source==='manual-with-photo'?' has-photo':''}"><b>${row.kind==='gas'?'Gas':'Water'}</b>${photoButton(row)}<strong>${row.value}</strong><small>${new Date(row.date).toLocaleString('en-AU')}${row.source==='bill-actual'?' · actual bill':''}${row.hasPhoto?' · photo':''}</small>${row.source==='bill-actual'?'<span class="gas-verified">Verified</span>':`<button data-delete-meter="${row.id}">Delete</button>`}</div>`).join('') : '<div class="chart-empty"><div><strong>No readings yet</strong>Add a manual reading or drop in a meter photo above.</div></div>';
    hydratePhotoThumbnails($('meterRecords'));
    document.querySelectorAll('[data-delete-meter]').forEach(button => button.addEventListener('click', async () => { await deleteReadingPhoto(button.dataset.deleteMeter); writeMeters(readMeters().filter(row => row.id !== button.dataset.deleteMeter)); renderMeters(); renderData(); window.dispatchEvent(new CustomEvent('homeinsights:meters-changed')); }));
  }
  function sourceRows() { const source = $('dataSource')?.value || 'daily'; if (source === 'meters') return readMeters().map(row => ({date:row.date,service:row.kind,reading:row.value,correctedReading:row.correctedReading??row.value,ocrOriginal:row.ocrOriginal??'',ocrAttempted:row.ocrAttempted??false,source:row.source,photo:row.hasPhoto?'saved':''})); if (source === 'live') return liveRows.slice().reverse(); return (window.HOME_INSIGHTS_DAILY || []).slice().reverse(); }
  function renderData() { const query = ($('dataSearch')?.value || '').toLowerCase(); let rows = sourceRows(); if (query) rows = rows.filter(row => JSON.stringify(row).toLowerCase().includes(query)); const keys = rows.length ? Array.from(new Set(rows.flatMap(row => Object.keys(row)))) : []; $('dataHead').innerHTML = keys.length ? `<tr>${keys.map(key => `<th>${key.replaceAll('_',' ')}</th>`).join('')}</tr>` : ''; $('dataBody').innerHTML = rows.map(row => `<tr>${keys.map(key => `<td>${row[key]??''}</td>`).join('')}</tr>`).join(''); $('dataEmpty').hidden = rows.length > 0; document.querySelector('.data-table-wrap')?.toggleAttribute('hidden', rows.length === 0); }
  function start() {
    const openEntry=kind=>{meterKind=kind;if(!document.getElementById('meters')?.classList.contains('active'))window.HomeInsightsRouter?.showPage('meters');$('meterKindLabel').textContent=meterKind==='gas'?'Gas meter':'Water meter';$('meterEntry').hidden=false;$('meterDate').value=localDateValue(new Date());$('meterValue').value='';clearSelectedPhoto();setTimeout(()=>$('meterEntry').scrollIntoView({behavior:'smooth',block:'start'}),120);};
    document.querySelectorAll('[data-open-meter]').forEach(button=>button.addEventListener('click',()=>openEntry(button.dataset.openMeter)));
    $('closeMeterEntry')?.addEventListener('click',()=>{clearSelectedPhoto();$('meterEntry').hidden=true;});
    $('meterPhoto')?.addEventListener('change',event=>handlePhoto(event.target.files?.[0]));$('removeMeterPhoto')?.addEventListener('click',clearSelectedPhoto);
    const drop=$('meterPhotoDrop');['dragenter','dragover'].forEach(type=>drop?.addEventListener(type,event=>{event.preventDefault();drop.classList.add('dragging');}));['dragleave','drop'].forEach(type=>drop?.addEventListener(type,event=>{event.preventDefault();drop.classList.remove('dragging');}));drop?.addEventListener('drop',event=>handlePhoto([...event.dataTransfer.files].find(file=>file.type.startsWith('image/'))));
    const gasPage=document.getElementById('gas');['dragenter','dragover'].forEach(type=>gasPage?.addEventListener(type,event=>{if(![...event.dataTransfer.items].some(item=>item.kind==='file'))return;event.preventDefault();gasPage.classList.add('gas-photo-drag');}));gasPage?.addEventListener('dragleave',event=>{if(!gasPage.contains(event.relatedTarget))gasPage.classList.remove('gas-photo-drag');});gasPage?.addEventListener('drop',event=>{event.preventDefault();gasPage.classList.remove('gas-photo-drag');const file=[...event.dataTransfer.files].find(item=>item.type.startsWith('image/'));if(!file)return;openEntry('gas');handlePhoto(file);});
    const waterPage=document.getElementById('water');['dragenter','dragover'].forEach(type=>waterPage?.addEventListener(type,event=>{if(![...event.dataTransfer.items].some(item=>item.kind==='file'))return;event.preventDefault();waterPage.classList.add('water-photo-drag');}));waterPage?.addEventListener('dragleave',event=>{if(!waterPage.contains(event.relatedTarget))waterPage.classList.remove('water-photo-drag');});waterPage?.addEventListener('drop',event=>{event.preventDefault();waterPage.classList.remove('water-photo-drag');const file=[...event.dataTransfer.files].find(item=>item.type.startsWith('image/'));if(!file)return;openEntry('water');handlePhoto(file);});
    $('saveMeterReading')?.addEventListener('click',async()=>{const raw=$('meterValue').value.trim().replace(',','.'),value=Number(raw),date=$('meterDate').value;if(!Number.isFinite(value)||value<0||!date){alert('Enter a valid cumulative meter reading and date.');return;}const iso=new Date(date).toISOString(),rows=readMeters();if(rows.some(row=>row.kind===meterKind&&row.date===iso)){alert('A reading for this meter already exists at that date and time.');return;}const id=crypto.randomUUID?crypto.randomUUID():String(Date.now());let hasPhoto=false;if(selectedPhotoFile){try{await photoOperation('put',id,await compactPhoto(selectedPhotoFile));hasPhoto=true;}catch(error){alert(`${error.message||'The photo could not be saved.'} The meter reading will still be saved.`);}}rows.push({id,kind:meterKind,value,correctedReading:value,ocrOriginal,ocrAttempted,date:iso,source:hasPhoto?'manual-with-photo':'manual',hasPhoto});writeMeters(rows);clearSelectedPhoto();$('meterEntry').hidden=true;renderMeters();renderData();window.dispatchEvent(new CustomEvent('homeinsights:meters-changed'));});
    window.addEventListener('homeinsights:live', event => { liveRows.push(event.detail); if (liveRows.length > 500) liveRows.shift(); if ($('dataSource')?.value === 'live') renderData(); });
    $('dataSource')?.addEventListener('change', renderData); $('dataSearch')?.addEventListener('input', renderData);
    $('downloadCsv')?.addEventListener('click', () => { const rows=sourceRows(); if(!rows.length){alert('There are no records to export yet.');return;} const keys=Array.from(new Set(rows.flatMap(row=>Object.keys(row)))); const escape=value=>`"${String(value??'').replaceAll('"','""')}"`; const csv=[keys.map(escape).join(','),...rows.map(row=>keys.map(key=>escape(row[key])).join(','))].join('\n'); const link=document.createElement('a'); link.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'})); link.download=`home-insights-${$('dataSource').value}.csv`; link.click(); URL.revokeObjectURL(link.href); });
    renderMeters(); renderData();
  }
  window.HomeInsightsLocalData = { start, renderMeters, renderData, hydratePhotoThumbnails, deleteReadingPhoto };
})();
