(() => {
  'use strict';
  const $=id=>document.getElementById(id),key='home-insights-meter-readings';let range='all';
  const money=v=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(v);
  const readings=()=>{try{return JSON.parse(localStorage.getItem(key)||'[]').filter(r=>r.kind==='water'&&Number.isFinite(Number(r.value))).map(r=>({...r,value:Number(r.value),time:new Date(r.date)})).sort((a,b)=>a.time-b.time)}catch{return[]}};
  function intervals(){const r=readings(),out=[];for(let i=1;i<r.length;i++){const days=(r[i].time-r[i-1].time)/86400000,diff=r[i].value-r[i-1].value;if(days>0&&diff>=0)out.push({start:r[i-1],end:r[i],days,litres:diff*1000,daily:diff*1000/days});}return out;}
  const date=d=>d.toLocaleDateString('en-AU',{day:'numeric',month:'short',year:'numeric'});
  function render(){const r=readings(),spans=intervals(),latest=spans.at(-1),bills=(window.HOME_INSIGHTS_WATER_BILLS||[]).slice(),lastBill=bills.at(-1);$('waterCoverage').textContent=r.length?`${r.length} meter readings · ${date(r[0].time)} to ${date(r.at(-1).time)}`:'No water meter readings saved yet';$('waterLatestDaily').textContent=latest?`${latest.daily.toFixed(0)} L/day`:'—';$('waterLatestPeriod').textContent=latest?`${date(latest.start.time)} – ${date(latest.end.time)}`:'Add two readings to calculate use';$('waterLatestBill').textContent=lastBill?money(lastBill.total):'—';$('waterLatestBillDate').textContent=lastBill?date(new Date(lastBill.date+'T12:00:00')):'No bill history';$('waterPageReading').textContent=r.length?r.at(-1).value.toLocaleString('en-AU'):'—';$('waterPageReadingDate').textContent=r.length?date(r.at(-1).time):'No reading saved';renderChart(bills,spans);$('waterReadingList').innerHTML=r.length?r.slice().reverse().map(x=>`<div class="gas-reading-row"><div><strong>${x.value.toLocaleString('en-AU')}</strong><small>${date(x.time)} · ${x.source||'manual'}</small></div></div>`).join(''):'<div class="gas-empty"><strong>No water readings yet</strong><span>Add a reading or drop a meter photo.</span></div>';}
  function renderChart(bills,spans){if(range==='365'){const cutoff=Date.now()-365*86400000;bills=bills.filter(b=>new Date(b.date)>=cutoff);spans=spans.filter(s=>s.end.time>=cutoff)}const W=1000,H=330,p={l:55,r:55,t:25,b:52},count=Math.max(bills.length,spans.length,1),x=i=>p.l+i/Math.max(1,count-1)*(W-p.l-p.r),billMax=Math.max(1,...bills.map(b=>b.total)),usageMax=Math.max(1,...spans.map(s=>s.daily)),base=H-p.b;let svg=`<svg viewBox="0 0 ${W} ${H}" role="img">`;for(let i=0;i<5;i++){const y=p.t+i*(base-p.t)/4;svg+=`<line class="water-grid" x1="${p.l}" x2="${W-p.r}" y1="${y}" y2="${y}"/>`}bills.forEach((b,i)=>{const h=b.total/billMax*(base-p.t),bw=Math.max(8,(W-p.l-p.r)/Math.max(1,bills.length)*.56);svg+=`<rect class="water-bill-bar" x="${x(i)-bw/2}" y="${base-h}" width="${bw}" height="${h}" rx="3"/><text class="water-x" x="${x(i)}" y="${H-20}">${new Date(b.date+'T12:00:00').toLocaleDateString('en-AU',{month:'short',year:'2-digit'})}</text>`});if(spans.length){const pts=spans.map((s,i)=>`${x(i)},${base-s.daily/usageMax*(base-p.t)}`).join(' ');svg+=`<polyline class="water-usage-line" points="${pts}"/>`}svg+='</svg>';$('waterChartV2').innerHTML=svg;}
  function start(){document.querySelectorAll('[data-water-range]').forEach(btn=>btn.addEventListener('click',()=>{range=btn.dataset.waterRange;document.querySelectorAll('[data-water-range]').forEach(b=>b.classList.toggle('active',b===btn));render()}));addEventListener('homeinsights:meters-changed',render);render();}
  window.HomeInsightsWaterV2={start,render};
})();
